### ISSUE TITLE
Couple tips & tricks

### ISSUE THREAD

**Issue by Barracuda72** [micouy/gniazdo-os#1]
I looked through code a bit and although I'm not in any way Rust expert (and still feel very sceptical about writing OS in Rust), I'd like to propose several improvements.

Lets's start from the `rust/src/main.rs`.
1. It's better to remove `#[feature(asm)]` (https://github.com/micouy/gniazdo-os/blob/master/rust/src/main.rs#L1), as it's only accepted by unstable compiler, but doesn't seem to be used anywhere in the code. (As a general advice, keep the ASM code separate, unless absolutely in the need.)
2. The only unsafe operation in `Video::print` (https://github.com/micouy/gniazdo-os/blob/master/rust/src/main.rs#L81) is writing to a location specified by the pointer, so it's the only line that should be wrapped in `unsafe {}`. Keep you `unsafe` to a bare minimum.

Next, let's go to the linker script, `link.lds`.
1. There's a `.rela` section defined (https://github.com/micouy/gniazdo-os/blob/master/link.ld#L15), that combines all `.rela*` sections from the object files. The truth is, you're performing the static linkage; there won't be any `.rela`'s. So `.rela` section would (well, at least should) be empty and, therefore, your nice alignment trick won't work too. It's better to remove `.rela` at all, or, if you still think you absolutely need it, move it before `.data` and move your magic alignment line in the `.data` (there always will be some `.data`).
2. There's no place in the linker script for the `.eh_frame`. I'm not sure (and not very interested) that causes it's appearance, but for me it was necessary to include it.
3. Tabs and spaces are mixed; that's not very good.

And, lastly, `Makefile`.
1. You're using `/usr/local/opt/llvm/bin/ld.lld` as a linker (https://github.com/micouy/gniazdo-os/blob/master/Makefile#L1). It's probably not very good idea, as that file won't exist on most systems. Using just $(LD) (default system linker) is a better option.
2. I advise you to use `-C lto -C opt-level=2` options for the Rust compiler. It'll make code size significantly smaller and at the same time will remove most parts of `core` crate along this their respective dependencies. (In fact, that way you could drop all this stupid `cargo`-ish stuff and just call compiler directly - but that's my personal opinion, and most hipsters won't agree with me on that.)
3. I also advise you to use `-C target-feature=-mmx,-sse,+soft-float` option. For the detailed explanation see here: https://os.phil-opp.com/disable-simd/ . In fact, you code crashes, if I don't add this, because your string is just perfectly long enough to trigger LLVM vectorizer.
4. Another advice is to put your main target on top, so it'll be the default one then you type `make` without parameters. Just a convenience thing.
5. You forgot to `clean` Rust intermediates (https://github.com/micouy/gniazdo-os/blob/master/Makefile#L7).
6. Floppy image in 2020 (https://github.com/micouy/gniazdo-os/blob/master/Makefile#L16)? Better use `-hda` option.

Didn't look much at the ASM code, so sorry, no feedback here.

**Comment by micouy** [comment]
Thanks! Sorry for not answering for so long. I'll review your suggestions in detail soon. Right now I can say a couple of things:

1. Some of the flags (`-C lto`, `-C target-feature=...` etc.) are defined in `target.json`. I'm not sure why the program crashes on your computer. Tell me if I did something wrong.
2. The `Makefile` will be replaced soon by a different tool I'm working on.
3. I've had some issues with cleaning Rust's files while using a custom target but I've already solved them.
4. IIRC the linker wouldn't link if I didn't have `.rela` sections in the script. Unfortunately I know very little about linking but I'll see what I can do about it. I'll definitely clean up the script.
5. For now this is an experimental project in an early stage of development. It isn't my main goal to make it work on every computer so I won't make the bulid process use the environmental variables. It's a great success if it least works on mine :)
6. I'll probably use `-hda`, I just didn't know the difference between it and `-fda`.
7. `src/main.rs` right now is a bit messy. I've been busy with other parts of the project and it'll change soon.

Thanks again. I really appreciate your feedback.

**Comment by Barracuda72** [comment]
> Sorry for not answering for so long. 

No, that's totally OK.

> Some of the flags (-C lto, -C target-feature=... etc.) are defined in target.json.

Ah, I see. I don't use Cargo, so I just changed Makefile to run `rustc` directly. I didn't even know there was something in `target.json`.

> The Makefile will be replaced soon by a different tool I'm working on.

Your project, your rules, of course, but in my opinion it's always better to use something standart, like Makefiles.

> IIRC the linker wouldn't link if I didn't have .rela sections in the script.

Don't know about the LLVM one (don't have it on my system), but GNU ld works fine and produces working binary.

> It isn't my main goal to make it work on every computer so I won't make the bulid process use the environmental variables.

Well, you're seem to be doing this in "tutorial-style", so I assumed you _are_ interested in making it work on as many computers as possible... Sorry if I made wrong assumption.

BTW, `$(LD)` isn't an environment variable; it's one of Make's [implicit variables](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html) and IIRC they are supported by all Make implementations (even Microsoft's NMake).

I'll peep from time to time for sure, 'cause I'm really interested in the question "Is it really worth to write an OS kernel in Rust, and therefore can Rust be considered as a system programming language?". As things stand now, the answer is "Definitely no", and several projects such as Redux prove it. But maybe there's something...

**Comment by micouy** [comment]
I'll consider leaving the Makefile. As to my tutorial style - I really want to share what I've learned with other people. But I'm a newbie and there are/will be tons of errors in my code and the way I use many tools. So I don't think of this project as a template to start building a kernel from. If you find it interesting, use it and I'll try to help you with what I know.
